### ISSUE TITLE
HScript vs Lua?

### ISSUE THREAD

**Issue by larsiusprime** [kevinresol/hare#3]
You mentioned that the targets are limited because of the Lua dependency. Is there any reason you want to go with Lua instead of [HScript](https://github.com/haxefoundation/hscript)? HScript should work on all targets that Haxe supports. (If you're dead set on Lua, that's totally cool, just wanted to check to see if other options could be helpful)

**Comment by kevinresol** [comment]
I tried hscript as first step but it is super slow on cpp

**Comment by larsiusprime** [comment]
Oh really? Interesting. You get better results with LUA then?

**Comment by kevinresol** [comment]
Yeah. But the major reason I used Lua is because of its coroutine feature, which allows me to write async scripts in a "straight" manner. Because scripting for rpg is mostly async, think showing a dialog we have to wait for the player to dismiss the dialog and then execute the next script function. For example, I can write in Lua something like:

``` lua
showMessage("some message");
showMessage("some message2");
showMessage("some message3");
```

instead of `showMessage("some message", onMessageFinishShowing);` that kind of async callback hell

**Comment by larsiusprime** [comment]
Yeah, sounds good. So just got to find some JS lua implementation I guess? Maybe write some externs for it?

**Comment by larsiusprime** [comment]
found this:
https://kripken.github.io/lua.vm.js/lua.vm.js.html

**Comment by kevinresol** [comment]
I wanted to enable lua in js and have come across this project too. But i forget exactly why i gave up at the end. Iirc it is because the js api is quite different from the C one

**Comment by larsiusprime** [comment]
Probably. Well, one thing at a time. Plenty of time to handle this later

**Comment by kevinresol** [comment]
We can utilize haxe's Lua target when it is out :smirk:
